version: '3'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-app

  todo-api:
    build: .
    container_name: todo-api
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo-app
      - PORT=5000
    networks:
      - todo-app

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - todo-app
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - todo-app

volumes:
  grafana_data:
  mongodb_data:

networks:
  todo-app:
    driver: bridge
